src/main/java/de/samply/share/client/model/db/tables/pojos/Configuration.java
/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Configuration implements Serializable {

    private static final long serialVersionUID = 599973995;

    private String  name;
    private String  setting;
    private Boolean visible;

    public Configuration() {}

    public Configuration(Configuration value) {
        this.name = value.name;
        this.setting = value.setting;
        this.visible = value.visible;
    }

    public Configuration(
        String  name,
        String  setting,
        Boolean visible
    ) {
        this.name = name;
        this.setting = setting;
        this.visible = visible;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSetting() {
        return this.setting;
    }

    public void setSetting(String setting) {
        this.setting = setting;
    }

    public Boolean getVisible() {
        return this.visible;
    }

    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Configuration (");

        sb.append(name);
        sb.append(", ").append(setting);
        sb.append(", ").append(visible);

        sb.append(")");
        return sb.toString();
    }
}

src/main/java/de/samply/share/client/control/CredentialsBean.java
/*
 * Copyright (c) 2017 Medical Informatics Group (MIG),
 * Universitätsklinikum Frankfurt
 *
 * Contact: www.mig-frankfurt.de
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */

package de.samply.share.client.control;

import de.samply.share.client.model.db.enums.AuthSchemeType;
import de.samply.share.client.model.db.enums.TargetType;
import de.samply.share.client.model.db.tables.pojos.Credentials;
import de.samply.share.client.util.db.CredentialsUtil;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * A ViewScoped backing bean used on the credentials page
 */
@ManagedBean(name = "credentialsBean")
@ViewScoped
public class CredentialsBean implements Serializable {

    private static final Logger logger = LogManager.getLogger(CredentialsBean.class);

    /** The credentials list. */
    private List<Credentials> credentialsList;

    @ManagedProperty(value = "#{configurationBean}")
    private ConfigurationBean configurationBean;

    private String newUsername;
    private String newPassword;
    private String newWorkstation;
    private String newDomain;
    private AuthSchemeType newAuthSchemeType;
    private TargetType newTargetType;

    public List<Credentials> getCredentialsList() {
        return credentialsList;
    }

    public void setCredentialsList(List<Credentials> credentialsList) {
        this.credentialsList = credentialsList;
    }

    public ConfigurationBean getConfigurationBean() {
        return configurationBean;
    }

    public void setConfigurationBean(ConfigurationBean configurationBean) {
        this.configurationBean = configurationBean;
    }

    public String getNewUsername() {
        return newUsername;
    }

    public void setNewUsername(String newUsername) {
        this.newUsername = newUsername;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public String getNewWorkstation() {
        return newWorkstation;
    }

    public void setNewWorkstation(String newWorkstation) {
        this.newWorkstation = newWorkstation;
    }

    public String getNewDomain() {
        return newDomain;
    }

    public void setNewDomain(String newDomain) {
        this.newDomain = newDomain;
    }

    public AuthSchemeType getNewAuthSchemeType() {
        return newAuthSchemeType;
    }

    public void setNewAuthSchemeType(AuthSchemeType newAuthSchemeType) {
        this.newAuthSchemeType = newAuthSchemeType;
    }

    public TargetType getNewTargetType() {
        return newTargetType;
    }

    public void setNewTargetType(TargetType newTargetType) {
        this.newTargetType = newTargetType;
    }

    @PostConstruct
    public void init() {
        refreshCredentials();
        newTargetType = TargetType.TT_CENTRALSEARCH;
    }

    /**
     * Refresh credentials list from Database.
     */
    public void refreshCredentials() {
        credentialsList = CredentialsUtil.fetchCredentials();
    }


    /**
     * Get all defined Auth Schemes
     *
     * Definition is done via an ENUM in the database
     *
     * @return an array of defined auth schemes
     */
    public AuthSchemeType[] getAuthSchemeTypes() {
        // TODO: Currently, SPNEGO and Kerberos are unsupported! Remove the filter here when they are (delete everything and uncomment the last line)
        AuthSchemeType[] authSchemeValues = AuthSchemeType.values();
        List<AuthSchemeType> credentialsList = new ArrayList<>();
        for (AuthSchemeType ast : authSchemeValues) {
            if (ast != AuthSchemeType.AS_KERBEROS && ast != AuthSchemeType.AS_SPNEGO && ast != AuthSchemeType.AS_APIKEY) {
                credentialsList.add(ast);
            }
        }

        return credentialsList.toArray(new AuthSchemeType[credentialsList.size()]);

        //return CredentialsType.values();
    }

    /**
     * Get an array of supported Auth Schemes for the given target type
     *
     * @param target what is the target of the authentication
     * @return an array of applicable auth schemes for the target
     */
    public AuthSchemeType[] getAuthSchemeTypes(TargetType target) {
        logger.debug("get auth scheme types called for target " + target);
        if (target == null) {
            return getAuthSchemeTypes();
        }
        switch (target) {
            case TT_LDM:
            case TT_CENTRALSEARCH:
            case TT_BROKER:
                AuthSchemeType[] authSchemeValues = new AuthSchemeType[1];
                authSchemeValues[0] = AuthSchemeType.AS_BASIC;
                return authSchemeValues;
            case TT_HTTP_PROXY:
            case TT_HTTPS_PROXY:
            default:
                return getAuthSchemeTypes();
        }
    }

    /**
     * Get an array of (database-) defined target types
     *
     * @return array of target types
     */
    public TargetType[] getTargetTypes() {
        return TargetType.values();
    }

    /**
     * Delete credentials from database.
     *
     * @param credentials
     *            the credentials to delete
     * @return the outcome for the jsf2 navigation
     */
    public String deleteCredentials(Credentials credentials) {
        CredentialsUtil.deleteCredentials(credentials);
        ApplicationBean.resetCredentialsProvider();
        return "credentials_list?faces-redirect=true";
    }

    /**
     * Add a new set of credentials and refresh the credentialsprovider
     */
    public void addCredentials() {
        Credentials newCredentials = new Credentials();
        newCredentials.setDomain(newDomain);
        newCredentials.setPasscode(newPassword);
        newCredentials.setTarget(newTargetType);
        if (newAuthSchemeType == null) {
            newCredentials.setAuthScheme(AuthSchemeType.AS_BASIC);
        } else {
            newCredentials.setAuthScheme(newAuthSchemeType);
        }
        newCredentials.setUsername(newUsername);
        newCredentials.setWorkstation(newWorkstation);
        CredentialsUtil.insertCredentials(newCredentials);
        clearNewCredentials();
        refreshCredentials();
        ApplicationBean.resetCredentialsProvider();
    }

    /**
     * Clear the Form
     */
    private void clearNewCredentials() {
        setNewDomain(null);
        setNewPassword(null);
        setNewTargetType(TargetType.TT_CENTRALSEARCH);
        setNewAuthSchemeType(AuthSchemeType.AS_BASIC);
        setNewUsername(null);
        setNewWorkstation(null);
    }
}

src/main/java/de/samply/share/client/control/UploadBean.java
/*
 * Copyright (c) 2017 Medical Informatics Group (MIG),
 * Universitätsklinikum Frankfurt
 *
 * Contact: www.mig-frankfurt.de
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */

package de.samply.share.client.control;

import de.samply.share.client.job.params.UploadJobParams;
import de.samply.share.client.model.EnumConfiguration;
import de.samply.share.client.model.db.enums.UploadStatusType;
import de.samply.share.client.model.db.tables.pojos.EventLog;
import de.samply.share.client.model.db.tables.pojos.Upload;
import de.samply.share.client.util.db.ConfigurationUtil;
import de.samply.share.client.util.db.EventLogUtil;
import de.samply.share.client.util.db.UploadUtil;
import de.samply.share.common.utils.SamplyShareUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.omnifaces.util.Messages;
import org.quartz.JobDataMap;
import org.quartz.JobKey;
import org.quartz.SchedulerException;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.List;

/**
 * ViewScoped backing bean that is used on upload related pages
 */
@ManagedBean(name = "uploadBean")
@ViewScoped
public class UploadBean implements Serializable {

    private static final Logger logger = LogManager.getLogger(UploadBean.class);

    @ManagedProperty(value = "#{loginBean}")
    private LoginBean loginBean;

    private List<Upload> uploads;

    private int selectedUploadId;
    private Upload selectedUpload;
    private List<EventLog> uploadEvents;

    private boolean dryrun;
    private boolean fullUpload;
    private boolean dktkFlagged = true;

    public LoginBean getLoginBean() {
        return loginBean;
    }

    public void setLoginBean(LoginBean loginBean) {
        this.loginBean = loginBean;
    }

    public List<Upload> getUploads() {
        return uploads;
    }

    public void setUploads(List<Upload> uploads) {
        this.uploads = uploads;
    }

    public int getSelectedUploadId() {
        return selectedUploadId;
    }

    public void setSelectedUploadId(int selectedUploadId) {
        this.selectedUploadId = selectedUploadId;
    }

    public Upload getSelectedUpload() {
        return selectedUpload;
    }

    public void setSelectedUpload(Upload selectedUpload) {
        this.selectedUpload = selectedUpload;
    }

    public List<EventLog> getUploadEvents() {
        return uploadEvents;
    }

    public void setUploadEvents(List<EventLog> uploadEvents) {
        this.uploadEvents = uploadEvents;
    }

    public boolean isDryrun() {
        return dryrun;
    }

    public void setDryrun(boolean dryrun) {
        this.dryrun = dryrun;
    }

    public boolean isFullUpload() {
        return fullUpload;
    }

    public void setFullUpload(boolean fullUpload) {
        this.fullUpload = fullUpload;
    }

    public boolean isDktkFlagged() {
        return dktkFlagged;
    }

    public void setDktkFlagged(boolean dktkFlagged) {
        this.dktkFlagged = dktkFlagged;
    }

    @PostConstruct
    public void init() {
        refreshUploadList();
    }

    /**
     * Load the selected upload (selected by view parameter) and the corresponding event log messages
     */
    public void loadSelectedUpload() {
        selectedUpload = UploadUtil.fetchUploadById(selectedUploadId);
        uploadEvents = EventLogUtil.fetchEventLogForUploadById(selectedUploadId);
    }

    /**
     * Reload the list of uploads from the database
     */
    private void refreshUploadList() {
        uploads = UploadUtil.fetchUploads();
    }

    /**
     * Spawn a new Upload to central search
     *
     * Depending on the setting of the switches on the page, spawn either an upload or dry run - a full or an incremental upload
     * and either upload patient datasets for patients with explicit dktk consent or those without that
     *
     * @return navigation information
     */
    public String spawnNewUpload() {
        int uploadId = storeUpload(dryrun, fullUpload, dktkFlagged);
        String jobName = dktkFlagged ? UploadJobParams.JOBNAME_DKTK : UploadJobParams.JOBNAME_NO_DKTK;
        JobKey jobKey = JobKey.jobKey(jobName, UploadJobParams.JOBGROUP);

        // Fill the JobDataMap for the trigger
        JobDataMap jobDataMap = new JobDataMap();
        jobDataMap.put(UploadJobParams.UPLOAD_ID, uploadId);
        jobDataMap.put(UploadJobParams.STATUS, UploadStatusType.US_NEW.getLiteral());
        jobDataMap.put(UploadJobParams.DKTK_FLAGGED, dktkFlagged);

        try {
            logger.info("Give Execute Job to scheduler for new upload");
            ApplicationBean.getScheduler().triggerJob(jobKey, jobDataMap);

            Messages.create("Upload Job spawned")
                    .detail("The Job has been spawned. It might take a while until it is completed.")
                    .add();
            return "upload_list?faces-redirect=true";
        } catch (SchedulerException e) {
            logger.error("Error spawning Upload Job", e);
            Messages.create("Upload Job could not be spawned")
                    .detail("An Scheduler Exception occurred: " + e.getMessage())
                    .error().add();
            return "";
        }
    }

    /**
     * Write the upload object to the database
     *
     * @return the database id of the upload
     */
    private int storeUpload(boolean dryrun, boolean fullUpload, boolean dktkFlagged) {
        Upload upload = new Upload();
        upload.setStatus(UploadStatusType.US_NEW);
        upload.setTriggeredAt(SamplyShareUtils.getCurrentSqlTimestamp());
        upload.setTriggeredBy(loginBean.getUser().getUsername());
        upload.setIsDryrun(dryrun);
        upload.setIsFullUpload(fullUpload);
        upload.setDktkFlagged(dktkFlagged);
        upload.setSuccessCount(0);
        upload.setFailureCount(0);
        return UploadUtil.insertUpload(upload);
    }

    /**
     * Check if any upload process is running at the moment
     *
     * @return true if an upload is active, false otherwise
     */
    public boolean isUploadRunning() {
        return (UploadUtil.getActiveUpload() != null);
    }

    /**
     * Cancel all upload related jobs
     */
    public void cancelUploadJobs() {
        Upload activeUpload = UploadUtil.getActiveUpload();
        activeUpload.setStatus(UploadStatusType.US_CANCELED);
        UploadUtil.updateUpload(activeUpload);
        ApplicationBean.cancelAllJobsForUpload();
    }

    public boolean isUploadNonDktkAllowed() {
        return ConfigurationUtil.getConfigurationElementValueAsBoolean(EnumConfiguration.CENTRAL_MDS_DATABASE_UPLOAD_PATIENTS_WITH_LOCAL_CONSENT);
    }
}

src/main/webapp/admin/configuration.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ Copyright (c) 2017 Medical Informatics Group (MIG),
  ~ Universitätsklinikum Frankfurt
  ~
  ~ Contact: www.mig-frankfurt.de
  ~
  ~ This program is free software; you can redistribute it and/or modify it under
  ~ the terms of the GNU Affero General Public License as published by the Free
  ~ Software Foundation; either version 3 of the License, or (at your option) any
  ~ later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but WITHOUT
  ~ ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  ~ FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  ~ details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program; if not, see <http://www.gnu.org/licenses>.
  ~
  ~ Additional permission under GNU GPL version 3 section 7:
  ~
  ~ If you modify this Program, or any covered work, by linking or combining it
  ~ with Jersey (https://jersey.java.net) (or a modified version of that
  ~ library), containing parts covered by the terms of the General Public
  ~ License, version 2.0, the licensors of this Program grant you additional
  ~ permission to convey the resulting work.
  -->
<ui:composition template="/WEB-INF/templates/globalTemplate.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:pass="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:o="http://omnifaces.org/ui"
                xmlns:sscl="http://java.sun.com/jsf/composite/samply-share-client"
                xmlns:wu="http://share.samply.de/webutils"
>
    <ui:param name="adminPage" value="true" />

    <ui:define name="title">#{msg.configuration_title}</ui:define>

    <ui:define name="metadata">
        <f:metadata>
            <f:viewAction action="#{configurationBean.init}" onPostback="false"/>
            <!--<f:viewAction action="#{credentialsController.refreshCredentials}" onPostback="true"/>-->
        </f:metadata>
    </ui:define>

    <ui:define name="additional-css">
        <h:outputStylesheet name="webjars/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css" />
        <h:outputStylesheet name="webjars/clockpicker/0.0.7/dist/bootstrap-clockpicker.min.css" />
        <h:outputStylesheet name="webjars/bootstrap-switch/3.3.2/css/bootstrap3/bootstrap-switch.min.css" />
    </ui:define>

    <ui:define name="additional-js">
        <h:outputScript name="webjars/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js" />
        <h:outputScript name="webjars/clockpicker/0.0.7/dist/bootstrap-clockpicker.min.js" />
        <h:outputScript name="webjars/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js" />
    </ui:define>

    <ui:define name="optional-import-constants">
        <o:importConstants type="de.samply.share.client.model.EnumConfiguration" />
        <o:importConstants type="de.samply.share.client.model.EnumConfigurationTimings" />
    </ui:define>

    <ui:define name="main-content">

        <h:form id="configurationForm" prependId="false">

            <ui:fragment rendered="#{wu:getProjectName() == 'dktk'}">
                <ui:include src="../WEB-INF/includes/c_configuration_centralMdsDb.xhtml" />
                <div class="form-space" />
            </ui:fragment>

            <ui:include src="../WEB-INF/includes/c_configuration_mdr.xhtml" />

            <div class="form-space" />

            <ui:include src="../WEB-INF/includes/c_configuration_interfaces.xhtml" />

            <div class="form-space" />

            <ui:include src="../WEB-INF/includes/c_configuration_monitoring.xhtml" />

            <div class="form-space" />

            <ui:include src="../WEB-INF/includes/c_configuration_proxy.xhtml" />

            <div class="form-space" />

            <ui:include src="../WEB-INF/includes/c_configuration_timings.xhtml" />

            <!-- Buttons -->
            <div class="form-space" />
            <hr />
            <h:messages id="messages" showSummary="true" showDetail="true" globalOnly="true" />

            <div class="row" style="margin-bottom: 50px;" >
                <div class="col-sm-12">
                    <h:commandButton styleClass="btn btn-md btn-primary pull-right" value="#{msg.common_save}"
                                     action="#{configurationBean.storeConfiguration}">
                        <f:ajax execute="@form" render="@form messages" onevent="bootstrapSwitchOn" />
                    </h:commandButton>
                </div>
            </div>
        </h:form>

        <ui:fragment rendered="#{wu:getProjectName() == 'dktk'}">
            <!--Put this outside the actual form because it contains a form itself-->
            <sscl:confirmUploadWithLocalConsentModal />
        </ui:fragment>
    </ui:define>

</ui:composition>

src/main/webapp/admin/upload_list.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ Copyright (c) 2017 Medical Informatics Group (MIG),
  ~ Universitätsklinikum Frankfurt
  ~
  ~ Contact: www.mig-frankfurt.de
  ~
  ~ This program is free software; you can redistribute it and/or modify it under
  ~ the terms of the GNU Affero General Public License as published by the Free
  ~ Software Foundation; either version 3 of the License, or (at your option) any
  ~ later version.
  ~
  ~ This program is distributed in the hope that it will be useful, but WITHOUT
  ~ ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  ~ FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  ~ details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program; if not, see <http://www.gnu.org/licenses>.
  ~
  ~ Additional permission under GNU GPL version 3 section 7:
  ~
  ~ If you modify this Program, or any covered work, by linking or combining it
  ~ with Jersey (https://jersey.java.net) (or a modified version of that
  ~ library), containing parts covered by the terms of the General Public
  ~ License, version 2.0, the licensors of this Program grant you additional
  ~ permission to convey the resulting work.
  -->

<ui:composition template="/WEB-INF/templates/globalTemplate.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:o="http://omnifaces.org/ui"
                xmlns:wu="http://share.samply.de/webutils"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:sscl="http://java.sun.com/jsf/composite/samply-share-client"
                xmlns:pass="http://xmlns.jcp.org/jsf/passthrough">
    <ui:param name="adminPage" value="true" />

    <ui:define name="title">#{msg.ull_title}</ui:define>

    <ui:define name="additional-css">
        <h:outputStylesheet name="webjars/datatables/1.10.13/css/dataTables.bootstrap.min.css"/>
        <h:outputStylesheet name="webjars/bootstrap-switch/3.3.2/css/bootstrap3/bootstrap-switch.min.css" />
    </ui:define>

    <ui:define name="additional-js">
        <h:outputScript name="webjars/datatables/1.10.13/js/jquery.dataTables.min.js"/>
        <h:outputScript name="webjars/datatables/1.10.13/js/dataTables.bootstrap.min.js"/>
        <h:outputScript name="webjars/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js" />
        <h:outputScript library="js" name="pages/upload_list.js"/>
        <h:outputScript library="js" name="date-de.js"/>
    </ui:define>

    <ui:define name="main-content">
        <h:form prependId="false">
            <o:commandScript name="updateButtonBar" render="upload-button-bar" execute="upload-button-bar" oncomplete="bootstrapSwitchOn()" />
            <div class="row" style="margin-bottom: 20px;">
                <ui:fragment rendered="#{wu:isCentralSearchPathSet()}">
                    <h:panelGroup layout="block" styleClass="col-xs-12" id="upload-button-bar">
                        <ui:fragment rendered="#{not uploadBean.uploadRunning}">
                            <fieldset>
                                <legend>
                                    <h:outputText value="#{msg.ull_manualUpload}" />
                                </legend>
                                <h:selectBooleanCheckbox value="#{uploadBean.dryrun}"
                                                         id="dryrunSwitch"
                                                         styleClass="switch"
                                                         pass:data-handle-width="100"
                                                         pass:data-label-width="100"
                                                         pass:data-on-text="#{msg.su_dryrun}"
                                                         pass:data-off-text="#{msg.su_upload}"
                                                         pass:data-on-color="default"/>

                                <h:selectBooleanCheckbox value="#{uploadBean.fullUpload}"
                                                         id="fullSwitch"
                                                         styleClass="switch"
                                                         pass:data-wrapper-class="wrapper-margin-left"
                                                         pass:data-handle-width="100"
                                                         pass:data-label-width="100"
                                                         pass:data-on-text="#{msg.su_full}"
                                                         pass:data-off-text="#{msg.su_incremental}"
                                                         pass:data-on-color="default"/>

                                <h:selectBooleanCheckbox value="#{uploadBean.dktkFlagged}"
                                                         id="dktkSwitch"
                                                         styleClass="switch"
                                                         readonly="#{not uploadBean.uploadNonDktkAllowed}"
                                                         pass:data-wrapper-class="wrapper-margin-left"
                                                         pass:data-handle-width="100"
                                                         pass:data-label-width="100"
                                                         pass:data-label-text="#{msg.su_dktk}"
                                                         pass:data-on-text="#{msg.common_yes}"
                                                         pass:data-off-text="#{msg.common_no}" />

                                <!--action="#{uploadBean.spawnNewUpload(dryrun.value, ignoreTimestamps.value, dktkFlagged.value)}"-->
                                <h:commandLink styleClass="btn btn-md btn-default"
                                               style="margin-left: 20px;"
                                               value="#{msg.ull_spawnUpload}"
                                               action="#{uploadBean.spawnNewUpload}"/>
                            </fieldset>
                        </ui:fragment>
                        <ui:fragment rendered="#{uploadBean.uploadRunning}">
                            <div class="btn-group btn-group-justified" role="group" >
                                <div class="btn-group" role="group">
                                    <h:commandLink styleClass="btn btn-md btn-default" value="#{msg.ull_cancelUpload}" action="#{uploadBean.cancelUploadJobs}"/>
                                </div>
                            </div>
                        </ui:fragment>
                    </h:panelGroup>
                </ui:fragment>
                <ui:fragment rendered="#{not wu:isCentralSearchPathSet()}">
                    <sscl:bootstrapPanel contextClass="panel-danger" headingText="#{msg.configuration_noCentralSearchPath}">
                        <f:facet name="bodyContent">
                            <h:outputText value="#{msg.configuration_noCentralSearchPathDetails}" />
                        </f:facet>
                    </sscl:bootstrapPanel>
                </ui:fragment>
            </div>
            <table id="upload-table" class="table table-hover">
                <thead>
                    <tr>
                        <th>#{msg.ull_id}</th>
                        <th>#{msg.ull_triggeredAt}</th>
                        <th>#{msg.ull_triggeredBy}</th>
                        <th>#{msg.ull_status}</th>
                    </tr>
                </thead>
                <tbody>
                    <ui:repeat var="upload" value="#{uploadBean.uploads}">
                        <tr>
                            <td>
                                <h:link outcome="show_upload" value="#{upload.id}">
                                    <f:param name="uploadId" value="#{upload.id}" />
                                </h:link>
                            </td>
                            <td>
                                <h:outputText value="#{wu:convertTime(upload.triggeredAt)}" styleClass="form-control-static"/>
                            </td>
                            <td>
                                <h:outputText value="#{upload.triggeredBy}" styleClass="form-control-static"/>
                            </td>
                            <td>
                                <h:outputText value="#{upload.status}" styleClass="form-control-static"/>
                            </td>
                        </tr>
                    </ui:repeat>
                </tbody>
            </table>
            <h:messages showDetail="true" showSummary="true" id="messages" globalOnly="true"/>
        </h:form>
    </ui:define>
</ui:composition>